DROP TABLE "ORDER" IF EXISTS ;

CREATE TABLE "ORDER" (
  id INTEGER IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL ,
  payment INTEGER NOT NULL ,
  status INTEGER DEFAULT 0 NOT NULL,
  address VARCHAR(50),
  creator VARCHAR(32) NULL ,
  modifier VARCHAR(32) NULL ,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  deleted INTEGER default '0' not null
);

COMMENT ON COLUMN "ORDER".payment IS '订单总额';
COMMENT ON COLUMN "ORDER".status IS '订单状态: 0-待支付,1-已支付.';
COMMENT ON COLUMN "ORDER".address IS '配送地址';

CREATE INDEX order_uid ON "ORDER" (user_id);


DROP TABLE "ORDER_ITEM" IF EXISTS ;

CREATE TABLE ORDER_ITEM (
  id  INTEGER IDENTITY PRIMARY KEY ,
  order_id INTEGER NOT NULL ,
  product_id INTEGER NOT NULL ,
  amount INTEGER NOT NULL ,
  creator VARCHAR(32) NULL ,
  modifier VARCHAR(32) NULL ,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  deleted INTEGER default '0' not null
);

ALTER TABLE ORDER_ITEM ADD FOREIGN KEY (order_id) REFERENCES "ORDER"(id);
-- ALTER TABLE ORDER_ITEM ADD FOREIGN KEY (product_id) REFERENCES PRODUCT(id);

