DROP TABLE user IF EXISTS ;

CREATE TABLE user (
  id   INTEGER IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  password VARCHAR(128) NOT NULL ,
  salt VARCHAR(128) NOT NULL ,
  mobile VARCHAR(20),
  creator VARCHAR(32) NULL ,
  modifier VARCHAR(32) NULL ,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  deleted INTEGER default '0' not null
);

CREATE INDEX user_name ON user (name);
